### PR TITLE
Classic branch

### PR DESCRIPTION
**Pull request by Metallicow**
Cleaned up the demos for ya. They should work with updated wx classic 2.8 - 2.9 and possibly further back to versions from old days they where originally wrote for. Some will work on Phoenix also. And basic preps for python 3 has been done. Ex: print('with parenthesis'). Also tried to trim trailing whitespace in all files.

Removed all the interpreter numbers from the shebangs. They were preventing users from attempting to run just because Ex: py24 or 25 wasn't installed. Also it is easier for the user to add interpreter numbers to the file shebang themselves when needed.

Basic pep8'd a lot of stuff for readability. Not the 79 chars per line style tho.
- Metalio Bovinus

### CODE REVIEW

**Comment by PythonCHB** [comment]
Hey thanks!

This looks great! It won't auto-merge, and I don't have time to go in and
figure out out right now, but I really look forward to checkign it out.

And it did need - I wrote some of those a good while ago with some pretty
ugly style...

I really appreciate the effort,

-Chris

On Sun, Dec 8, 2013 at 10:05 PM, Metallicow notifications@github.comwrote:

> Cleaned up the demos for ya. They should work with updated wx classic 2.8
> - 2.9 and possibly further back to versions from old days they where
>   originally wrote for. Some will work on Phoenix also. And basic preps for
>   python 3 has been done. Ex: print('with parenthesis'). Also tried to trim
>   trailing whitespace in all files.
> 
> Removed all the interpreter numbers from the shebangs. They were
> preventing users from attempting to run just because Ex: py24 or 25 wasn't
> installed. Also it is easier for the user to add interpreter numbers to the
> file shebang themselves when needed.
> 
> Basic pep8'd a lot of stuff for readability. Not the 79 chars per line
> style tho.
> - Metalio Bovinus
> 
> ---
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/Metallicow/wxPythonDemos Classic-Branch
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/PythonCHB/wxPythonDemos/pull/1
> Commit Summary
> - Fix Shebang/CleanWS/print('Parenthesis')/**main**
> - Fix Shebang/Cleanup/Readability
> - Cleanup/FONT/Readability
> - Cleanup/Generator/Remove Unneeded
> - Cleanup/Shebang/print("PY3")/General Fixes
> 
> File Changes
> - _M_ AboutDialog.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-0(26)
> - _M_ Append_test.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-1(29)
> - _M_ BitmapFromBufferTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-2(4)
> - _M_ BitmapFromPILTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-3(2)
> - _M_ BlitTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-4(12)
> - _M_ BufferedWithControls.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-5(4)
> - _M_ ButtonArray.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-6(16)
> - _M_ CalculatorDemo.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-7(12)
> - _M_ CalculatorDemoDriver.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-8(12)
> - _M_ CenterTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-9(2)
> - _M_ ChangePanel.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-10(128)
> - _M_ ChoiceTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-11(18)
> - _M_ ClickBitmap.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-12(20)
> - _M_ ClientDCTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-13(65)
> - _M_ Clock.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-14(32)
> - _M_ DisplayRes.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-15(23)
> - _M_ DoubleBufferDemo.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-16(69)
> - _M_ DoubleBufferTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-17(87)
> - _M_ DrawLinesTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-18(56)
> - _M_ DrawOnControl.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-19(58)
> - _M_ EllipticArcTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-20(14)
> - _M_ FontSizeTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-21(34)
> - _M_ FrameFlags.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-22(24)
> - _M_ GenStaticBitmap.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-23(32)
> - _M_ GridBagSizer.1.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-24(22)
> - _M_ GridBagSizer.2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-25(17)
> - _M_ HTML_tester.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-26(19)
> - _M_ ImageInHtml.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-27(12)
> - _M_ ImageNumpy.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-28(51)
> - _M_ ImageWindow.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-29(17)
> - _M_ Jeopardy.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-30(66)
> - _M_ KeyPressDraw.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-31(38)
> - _M_ LamdaTrick.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-32(25)
> - _M_ MPLmath.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-33(48)
> - _M_ MacApp.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-34(53)
> - _M_ MacAppsetup.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-35(4)
> - _M_ MicroApp.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-36(22)
> - _M_ MoveText.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-37(7)
> - _M_ MultiFrame.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-38(33)
> - _M_ NewSizertest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-39(33)
> - _M_ OffScreenHTML.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-40(50)
> - _M_ Overlaytest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-41(64)
> - _M_ Overlaytest2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-42(36)
> - _M_ PaintDemo.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-43(66)
> - _M_ PassArgsToCallback.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-44(56)
> - _M_ Popup.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-45(35)
> - _M_ ProceduralTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-46(79)
> - _M_ RadioBox.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-47(31)
> - _M_ RotatedText.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-48(44)
> - _M_ ScrolledBitmap.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-49(70)
> - _M_ SelectText.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-50(51)
> - _M_ SeparateThread.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-51(22)
> - _M_ SimpleSizer.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-52(31)
> - _M_ SimpleSizer2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-53(41)
> - _M_ SimpleSizer3.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-54(53)
> - _M_ SimpleSizer4.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-55(34)
> - _M_ SizerTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-56(93)
> - _M_ SizerTest2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-57(138)
> - _M_ SizerTest3.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-58(31)
> - _M_ SplashScreen.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-59(68)
> - _M_ StaticBitmap.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-60(83)
> - _M_ StaticTextSizer.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-61(31)
> - _M_ StyleApp.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-62(29)
> - _M_ TestEvents.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-63(56)
> - _M_ TestHTML.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-64(41)
> - _M_ TestUpdate.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-65(48)
> - _M_ TestUpdate2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-66(63)
> - _M_ TestUpdate3.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-67(57)
> - _M_ TestWrap.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-68(24)
> - _M_ TimerDemo.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-69(46)
> - _M_ TimerDemo2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-70(26)
> - _M_ TimerDemo3.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-71(62)
> - _M_ ToolBarSimple.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-72(37)
> - _M_ ToolTips.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-73(57)
> - _M_ UnicodeTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-74(22)
> - _M_ Validator.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-75(21)
> - _M_ WebKit.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-76(19)
> - _M_ WheelTest.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-77(24)
> - _M_ XOR_test.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-78(20)
> - _M_ csv_tool.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-79(67)
> - _M_ icons.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-80(14)
> - _M_ ieWin_test.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-81(35)
> - _M_ lupa.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-82(37)
> - _M_ lupa2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-83(44)
> - _M_ multibox2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-84(105)
> - _M_ print6.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-85(83)
> - _M_ scrolleddoublebuffer2.5.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-86(170)
> - _M_ scrolleddoublebuffer2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-87(87)
> - _M_ sudoku-chb.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-88(92)
> - _M_ test_overlay.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-89(28)
> - _M_ test_overlay2.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-90(43)
> - _M_ testdc.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-91(48)
> - _M_ testtext.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-92(40)
> - _M_ toolbardemo.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-93(148)
> - _M_ wxProject.pyhttps://github.com/PythonCHB/wxPythonDemos/pull/1/files#diff-94(16)
> 
> Patch Links:
> - https://github.com/PythonCHB/wxPythonDemos/pull/1.patch
> - https://github.com/PythonCHB/wxPythonDemos/pull/1.diff

## 

Christopher Barker, PhD

Python Language Consulting
- Teaching
- Scientific Software Development
- Desktop GUI and Web Development
- wxPython, numpy, scipy, Cython

**Comment by Metallicow** [comment]
Not sure why it doesn't want to auto merge... I used the newer github for windows UI. It seems alright but coould be a improved a small bit in some areas. Not sure if this is related to the github gui... It has a simple UI which is easy enough for a drag and drop environment. I was looking for something to speed test my SourceCoder's auto-check features with and noticed it was a simple enough bunch of demos worth while. I even learned a few things, esp about converting the old syntax style. :)
You could easily check it out to your desktop and use a diff tool such as winmerge to merge the changes from your last two commits into it then reup all that as a new commit.
It says I started when you only had 3 commits. probably not a whole lot was changed, since it seems you are at five now. You may want to skim over it, before making a new commit as there are probably a few "here" and "there" small misses with the readability stuff.
Here is a pic of the history in the github gui, if it helps.
http://img96.imageshack.us/img96/2438/aryt.png

**Comment by PythonCHB** [comment]
On Mon, Dec 9, 2013 at 10:07 PM, Metallicow notifications@github.comwrote:

> Not sure why it doesn't want to auto merge...
> 
> usually that means there is a conflict -- i.e. you and I both changed the
> same thing. Probably only one or two, but that's all it takes.

You may want to skim over it, before making a new commit as there are

> probably a few "here" and "there" small misses with the readability stuff.
> 
> yup, and I'll need to resolve the conflicts anyway.
> 
> Here is a pic of the history in the github gui, if it helps.
> http://img96.imageshack.us/img96/2438/aryt.png

Thanks -- but it'll all in the commit, so no problem.

Thanks again,
   -Chris

## 

Christopher Barker, PhD

Python Language Consulting
- Teaching
- Scientific Software Development
- Desktop GUI and Web Development
- wxPython, numpy, scipy, Cython

**Comment by PythonCHB** [comment]
It's only been 5 years, but I was updating some stuff, so figured I might as well merge all this.

There are a LOT that have not been updated for wxPy4, but closer now...

**Comment by Metallicow** [comment]
Yep, yep. Sometimes things are better in little bits then all at once. Thanks for the time spent. 
plz dont run that thru the interpreter :)

**Pull request merged**
